import type { Vault } from '@/features/vault/components/VaultCard'

export const MOCK_VAULTS: Vault[] = [
  {
    id: 'delta-neutral-usdc',
    name: 'Delta Neutral USDC',
    asset: 'USDC',
    apy: 12.4,
    tvl: 2400000,
    tvlFormatted: '$2.4M',
    risk: 'low',
    status: 'active',
    strategy: 'Delta Neutral',
    goal: 'delta-neutral',
    minDeposit: 100,
    description: 'Earn stable yield from funding rates with minimal directional risk.',
    withdrawalTime: '2–3 days',
    liquidity: 'High',
    rewards: ['Harmonix'],
    isRecommended: false,
    depositorCount: 3200,
    yieldSources: [
      { label: 'Funding Rates', pct: 55 },
      { label: 'Lending', pct: 30 },
      { label: 'Incentives', pct: 15 },
    ],
    depositTokens: [
      { label: 'USDC', color: 'bg-blue-500', textColor: 'text-white' },
    ],
    apy30d: 12.1,
    apy90d: 11.8,
  },
  {
    id: 'eth-yield-max',
    name: 'ETH Yield Max',
    asset: 'ETH',
    apy: 18.2,
    tvl: 1200000,
    tvlFormatted: '$1.2M',
    risk: 'medium',
    status: 'active',
    strategy: 'Yield Optimized',
    goal: 'growth',
    minDeposit: 250,
    description: 'Optimized ETH yield combining staking, lending, and liquidity provision.',
    withdrawalTime: '3–5 days',
    liquidity: 'Medium',
    rewards: ['Harmonix'],
    isRecommended: true,
    depositorCount: 5100,
    yieldSources: [
      { label: 'Staking', pct: 40 },
      { label: 'Lending', pct: 35 },
      { label: 'Liquidity', pct: 25 },
    ],
    depositTokens: [
      { label: 'ETH', color: 'bg-indigo-500', textColor: 'text-white' },
      { label: 'wETH', color: 'bg-indigo-700', textColor: 'text-white' },
    ],
    apy30d: 17.9,
    apy90d: 16.4,
  },
  {
    id: 'btc-bull-run',
    name: 'BTC Bull Run',
    asset: 'BTC',
    apy: 24.8,
    tvl: 890000,
    tvlFormatted: '$890K',
    risk: 'high',
    status: 'active',
    strategy: 'Directional',
    goal: 'high-yield',
    minDeposit: 500,
    description: 'Directional BTC strategy designed to capture upside momentum.',
    withdrawalTime: '5–7 days',
    liquidity: 'Low',
    rewards: ['Harmonix'],
    depositorCount: 1800,
    yieldSources: [
      { label: 'Momentum', pct: 60 },
      { label: 'Options', pct: 25 },
      { label: 'Incentives', pct: 15 },
    ],
    depositTokens: [
      { label: 'BTC', color: 'bg-orange-500', textColor: 'text-white' },
      { label: 'wBTC', color: 'bg-orange-700', textColor: 'text-white' },
    ],
    apy30d: 22.3,
    apy90d: 19.7,
  },
  {
    id: 'stable-plus',
    name: 'Stable Plus',
    asset: 'USDC',
    apy: 8.6,
    tvl: 4100000,
    tvlFormatted: '$4.1M',
    risk: 'low',
    status: 'active',
    strategy: 'Yield Optimized',
    goal: 'stable-income',
    minDeposit: 100,
    description: 'Ultra-conservative stablecoin strategy for capital preservation.',
    withdrawalTime: '1–2 days',
    liquidity: 'High',
    rewards: ['Harmonix'],
    depositorCount: 8400,
    yieldSources: [
      { label: 'Lending', pct: 65 },
      { label: 'Treasury', pct: 25 },
      { label: 'Incentives', pct: 10 },
    ],
    depositTokens: [
      { label: 'USDC', color: 'bg-blue-500', textColor: 'text-white' },
      { label: 'USDT', color: 'bg-emerald-500', textColor: 'text-white' },
    ],
    apy30d: 8.4,
    apy90d: 8.2,
  },
  {
    id: 'hype-momentum',
    name: 'HYPE Momentum',
    asset: 'HYPE',
    apy: 31.2,
    tvl: 560000,
    tvlFormatted: '$560K',
    risk: 'high',
    status: 'active',
    strategy: 'Directional',
    goal: 'high-yield',
    minDeposit: 200,
    description: 'High-conviction HYPE token strategy exploiting momentum signals.',
    withdrawalTime: '5–7 days',
    liquidity: 'Low',
    rewards: ['Harmonix'],
    depositorCount: 2200,
    apy30d: 29.4,
    yieldSources: [
      { label: 'Momentum', pct: 50 },
      { label: 'Funding Rates', pct: 30 },
      { label: 'Incentives', pct: 20 },
    ],
    depositTokens: [
      { label: 'HYPE', color: 'bg-primary', textColor: 'text-primary-foreground' },
    ],
  },
  {
    id: 'balanced-yield',
    name: 'Balanced Yield',
    asset: 'USDC',
    apy: 15.1,
    tvl: 1800000,
    tvlFormatted: '$1.8M',
    risk: 'medium',
    status: 'active',
    strategy: 'Delta Neutral',
    goal: 'stable-income',
    minDeposit: 150,
    description: 'Balanced mix of stable and growth strategies.',
    withdrawalTime: '2–3 days',
    liquidity: 'Medium',
    rewards: ['Valantis', 'Harmonix'],
    depositorCount: 4600,
    yieldSources: [
      { label: 'Funding Rates', pct: 45 },
      { label: 'Lending', pct: 35 },
      { label: 'Incentives', pct: 20 },
    ],
    depositTokens: [
      { label: 'USDC', color: 'bg-blue-500', textColor: 'text-white' },
    ],
  },
]

export const MOCK_VAULT_DETAIL = {
  'delta-neutral-usdc': {
    strategyDetail: 'Maintains a delta-neutral position via simultaneous long and short exposure. Yield generated from perpetual funding rates.',
    allocationBreakdown: [
      { label: 'Long Perps', percent: 48, color: 'bg-primary' },
      { label: 'Short Perps', percent: 48, color: 'bg-muted-foreground' },
      { label: 'Cash Reserve', percent: 4, color: 'bg-border' },
    ],
    riskDetails: [
      { title: 'Funding Rate Risk', body: 'Rates can turn negative in extreme market conditions, temporarily reducing yield.' },
      { title: 'Smart Contract Risk', body: 'All contracts are audited, but no code is 100% risk-free.' },
      { title: 'Operator Risk', body: 'Strategy performance depends on execution quality and rebalancing frequency.' },
    ],
    withdrawalTime: '2–3 days',
    audited: true,
    auditDate: 'December 2024',
    operator: 'Harmonix',
    launchDate: 'January 2024',
  },
}
